version: '3'

tasks:

  BaseBuildAllCodeunits:
    desc: "Base: Build all codeunits"
    silent: true
    dir: "."
    cmds:
      - scbuildcodeunits
    aliases:
      - basebuildallcodeunits
      - bb

  paperserverRunExample:
    desc: "PaperServer: Run example"
    silent: true
    dir: "."
    cmds:
      - python PaperServer/Other/Reference/ReferenceContent/Examples/MinimalDockerComposeFile/RunExample.py
    aliases:
      - paperserverrunexample
