version: '3'

tasks:

  BaseBuildAllCodeunits:
    desc: "Base: Build all codeunits"
    silent: true
    dir: "."
    cmds:
      - "scbuildcodeunits {{.CLI_ARGS}}"
    aliases:
      - basebuildallcodeunits
      - bb

  PaperserverRunExample:
    desc: "PaperServer: Run example"
    silent: true
    dir: "."
    cmds:
      - "python PaperServer/Other/Reference/ReferenceContent/Examples/MinimalDockerComposeFile/RunExample.py {{.CLI_ARGS}}"
    aliases:
      - paperserverrunexample
